### ISSUE TITLE
Goopy Blocks Fix

### ISSUE THREAD

**Issue by PssbleTrngle** [TeamGalena/oreganized#31]
Make all goopy blocks react to hot blocks quicker. Aside of getting into the "Purple Hot" State when next to Lava, Magma block or Molten Lead, Add a mechanic where if a lead block is right next to a light emitting block that emits the light level of 15(like a torch) it will go into the goopy state.

Both goopy and Purple hot Blocks will emit light level of 3

**Comment by PssbleTrngle** [comment]
Not entirely sure if making them react quicker is worth it. Currently it works using random ticks (like crops, copper, leaves, ...). Making them react faster could be solved by them reacting to block updates next to them, which should be doable, or requiring a kind of ticking block entity which would be a huge performance drop

**Comment by x-agentM-x** [comment]
When I played around with it it was super slow so mabye reach some kind of balance with the speed of the change and performace?

**Comment by x-agentM-x** [comment]
Also, fire and campfires should also make lead blocks red hot
