### ISSUE TITLE
Lead Bulb

### ISSUE THREAD

**Issue by PssbleTrngle** [TeamGalena/oreganized#32]
New kind of Bulb that isn't affected by redstone, instead it's ability to emit light gets diminshed based on how hot it gets.
1- default emits 13 light level
2 - If its next to a goopy block its ability to emit light decreases to 6 light level
1 - If it is goopy itself it will no longer emit light as it's supposed to and only emits 3 as all other goopy blocks

Crafting is 3 lead ingots - 1, molten lead bucket - 2, glow ink sac - 3.
0 1 0
1 3 1
0 1 0

**Comment by PssbleTrngle** [comment]
I don't quite understand the recipe, I think you got something about the numbers wrong.

**Comment by x-agentM-x** [comment]
Yeah i think i messed it up lmao
Crafting is lead ingot - 1, molten lead bucket(you get back the bucket after crafting!) - 2.
0 1 0
1 2 1
0 1 0
