### ISSUE TITLE
Lead ingot recipe id doesn't follow vanilla recipe naming conventions

### ISSUE THREAD

**Issue by thelegitdolt** [TeamGalena/oreganized#58]
### What happened?

The recipe that crafts 3x3 nuggets to ingots is called `{modid}:{ingot name}_ingot_from_nuggets` in vanilla minecraft, but 
<img width="1000" alt="Screenshot 2024-10-24 at 3 09 12 PM" src="https://github.com/user-attachments/assets/d617e376-a647-44f5-b2e5-bea006acf642">
This recipe is called oreganized is just called `oreganized:lead_ingot`. 

It should be called `oreganized:lead_ingot_from_nuggets`

### Mod Version

3.1.0

### Minecraft Version

1.20

**Comment by thelegitdolt** [comment]
<img width="1114" alt="Screenshot 2024-10-24 at 3 10 00 PM" src="https://github.com/user-attachments/assets/bf311a7b-3ea2-4422-9429-f9fd659aa88f">
It breka my crafttweaker script !!!

**Comment by PssbleTrngle** [comment]
I guess we could change that
