### ISSUE TITLE
Lead bolts cause armor duplication

### ISSUE THREAD

**Issue by Yurisan001** [TeamGalena/oreganized#63]
### What happened?

Shooting a lead bolt at a mob that doesn't normally drop armor will cause it to drop.
This causes a duplication glitch with mobs that duplicate equipment, such as the mimicube in Alex's mobs and the mime in Cavern and Chasms(from github).

### Mod Version

3.1.0

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Should add a blacklist entity tag for those
