### ISSUE TITLE
shovels not working properly in version 3.1.1

### ISSUE THREAD

**Issue by EkoDy** [TeamGalena/oreganized#67]
### What happened?

When using mod version 3.1.1, shovels (both enchanted and unenchanted) stop working properly and dig as slowly as a bare fist.
I have already tried disabling the mod and reverting back to version 3.1.0, and in both cases the shovels worked properly.
I also tried running a modpack with only oreganized 3.1.1, and the problem was still there.

### Mod Version

3.1.1

### Minecraft Version

1.20

**Comment by PssbleTrngle** [comment]
Looks like a broke another #mineable tag, will take a look at it
