### ISSUE TITLE
Blocks with the `oreganized:blows_lead_cloud` block tag not spawning lead clouds when broken

### ISSUE THREAD

**Issue by meeprdib** [TeamGalena/oreganized#68]
### What happened?

Expected result - 
Blocks tagged with the `oreganized:blows_lead_cloud` tag should summon lead clouds when broken

Actual result - 
Blocks with the tag are broken normally.

![image](https://github.com/user-attachments/assets/d01502a7-3570-4f29-828d-ee2ec9c66db1)
![image](https://github.com/user-attachments/assets/0ddcbe0e-e5d2-4c3e-96e4-01567b2ee5af)

### Mod Version

3.1.0

### Minecraft Version

1.20

**Comment by meeprdib** [comment]
Did some more testing, seems like the tag is completely nonfunctional. Removing `oreganized:lead_ore` from the tag did nothing from preventing it from spawning the clouds.
![image](https://github.com/user-attachments/assets/28a236a2-a16a-4eb7-998d-d0ca8b42f249)
![image](https://github.com/user-attachments/assets/37638108-8940-4d23-829a-a3c18d65b39a)

**Comment by meeprdib** [comment]
Since the tag does nothing, why attempt to assign it to blocks via tags?
https://github.com/TeamGalena/oreganized/blob/1.20.x/src/generated/resources/data/oreganized/tags/blocks/blows_lead_cloud.json
You cannot assign block tags from item tags this way.

**Comment by PssbleTrngle** [comment]
That is not what this tag is for, it's used for the create/supplementaries compat where fans & bellows can blow off lead clouds from these blocks.

I will convert this into a feature request tho to move the cloud on breaking mechanic to also move to a tag-based system
