### ISSUE TITLE
Incompatible with Overweight Farming

### ISSUE THREAD

**Issue by Junnaturefox** [TeamGalena/oreganized#9]
Minecraft version: 1.18.2
Overweight Farming version: 1.6.0
Oreganized version: 2.0.0

After installing the two mods together, the game will crash immediately when it starts
[https://paste.ee/p/X6WOE](https://paste.ee/p/X6WOE)

`Exception in thread "main" java.lang.module.ResolutionException: Modules oreganized and overweight_farming export package galena.galenacapes to module forge`

**Comment by Xaidee** [comment]
Fixed for now in 2.0.1 by disabling Supporter Capes, I need to re-implement them in a way that doesn't break in the future
